### ISSUE TITLE
./train.sh TrainPhase1.  tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)

### ISSUE THREAD

**Issue by Yuanzizizi** [mit-acl/rl_collision_avoidance#11]
When I run ./train.sh TrainPhase1, I get this ....

`--------------------------------------------------------------------------------------------------------------
Running GA3C-CADRL gym-collision-avoidance training script (TrainPhase1)
---------------------------------------------------------------------------------------------------------------
[Server] Making model...
[Server] Loading Regression Model then training RL.
[NetworkVPCore] Loading checkpoint file: /home/rl_collision_avoidance/ga3c/GA3C/checkpoints/regression/wandb/run-rnn/checkpoints/network_00000000
Traceback (most recent call last):
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Run.py", line 74, in <module>
    Server().main()
  File "/home/rl_collision_avoidance/ga3c/GA3C/Server.py", line 66, in __init__
    self.model.load(learning_method='regression')
  File "/home/rl_collision_avoidance/ga3c/GA3C/NetworkVPCore.py", line 246, in load
    self.saver.restore(self.sess, filename)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
	 [[node save/RestoreV2 (defined at /home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "Run.py", line 74, in <module>
    Server().main()
  File "/home/rl_collision_avoidance/ga3c/GA3C/Server.py", line 57, in __init__
    self.model = self.make_model()
  File "/home/rl_collision_avoidance/ga3c/GA3C/Server.py", line 83, in make_model
    return globals()[Config.NET_ARCH](Config.DEVICE, Config.NETWORK_NAME, self.num_actions) # TODO can probably change Config.NETWORK_NAME to Config.NET_ARCH
  File "/home/rl_collision_avoidance/ga3c/GA3C/NetworkVP_rnn.py", line 37, in __init__
    super(self.__class__, self).__init__(device, model_name, num_actions)
  File "/home/rl_collision_avoidance/ga3c/GA3C/NetworkVPCore.py", line 57, in __init__
    self.saver = tf.compat.v1.train.Saver({var.name: var for var in vars}, max_to_keep=0)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/rl_collision_avoidance/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
`
How to solve it? I really need your help. Thanks~

**Comment by mfe7** [comment]
This seems like an issue in loading a pre-trained network file. I think I've seen things like this when I created / loaded model files on different versions of python/tensorflow, but I don't have a specific fix in mind. This seems like a more general issue tensorflow users would have seen and addressed before, e.g., https://github.com/tensorflow/models/issues/2675

**Comment by Yuanzizizi** [comment]
Thanks ~

I finally solved this problem referring to #7 .
