### ISSUE TITLE
python: can't open file 'setup.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Adnan-annan** [mit-acl/rl_collision_avoidance#3]
Hi thanks for sharing your awesome work. while running ./install.sh i encounter this problem . Can you help me solve this ?

**Comment by mfe7** [comment]
I've gotten that error when trying to install the RVO submodule, particularly when I hadn't initialized the submodule or cloned the repo recursively

**Comment by HanBing0802** [comment]
> I've gotten that error when trying to install the RVO submodule, particularly when I hadn't initialized the submodule or cloned the repo recursively

hi, while running ./install.sh, I encounter this problem as follows.
`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/hb/.local/lib/python3.5/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/home/hb/.local/lib/python3.5/site-packages/virtualenv/run/__init__.py", line 12, in <module>
    from .plugin.activators import ActivationSelector
  File "/home/hb/.local/lib/python3.5/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/home/hb/.local/lib/python3.5/site-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    from importlib_metadata import entry_points
  File "/home/hb/.local/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 88
    dist: Optional['Distribution'] = None
        ^
SyntaxError: invalid syntax`

Can you help me solve this? Thanks!
